// Copyright 2026 rcllite contributors
// Licensed under the Apache License, Version 2.0
//
// Message type trait.  Every message type usable with rcllite — hand-written
// or generated by tools/msg_codegen.py — specializes MessageType<T>:
//
//   template<>
//   struct rcl::MessageType<std_msgs::msg::String>
//   {
//     static const char * dds_name();               // "std_msgs::msg::dds_::String_"
//   };
//
// Serialization lives on the message struct itself (static serialize /
// deserialize members).  Service types provide nested `Request` / `Response`
// structs; each of those gets its own MessageType<> specialization (their DDS
// names are "pkg::srv::dds_::Name_Request_" / "..._Response_").
#ifndef RCLLITE__MSG_TRAITS_HPP_
#define RCLLITE__MSG_TRAITS_HPP_

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

#include "rcllite/cdr.hpp"

namespace rcl {

template <typename T>
struct MessageType;  // intentionally undefined

// --- helpers for hand-written message types ---------------------------------
//
// Wire rules (matching rmw): sequence length prefixes are uint32 and always
// 4-aligned; elements keep their own alignment after the length.

template <typename T, typename SerializeElem>
void write_sequence(CdrWriter& w, const std::vector<T>& v,
                    SerializeElem serialize_elem) {
  w.align_to(4);
  w.write_uint32(static_cast<uint32_t>(v.size()));
  for (const auto& e : v) {
    serialize_elem(w, e);
  }
}

/// The remaining-bytes guard rejects corrupt lengths before a huge
/// allocation (every element needs at least one byte).
template <typename T, typename DeserializeElem>
bool read_sequence(CdrReader& r, std::vector<T>& v, DeserializeElem deserialize_elem) {
  r.align_to(4);
  const uint32_t n = r.read_uint32();
  if (n > r.remaining()) {
    return false;
  }
  v.clear();
  v.reserve(n);
  for (uint32_t i = 0; i < n; ++i) {
    T e{};
    if (!deserialize_elem(r, e)) {
      return false;
    }
    v.push_back(std::move(e));
  }
  return true;
}

/// std::vector<std::string> helpers.
inline void write_string_sequence(CdrWriter& w, const std::vector<std::string>& v) {
  write_sequence(w, v, [](CdrWriter& w, const std::string& s) { w.write_string(s); });
}

inline bool read_string_sequence(CdrReader& r, std::vector<std::string>& v) {
  return read_sequence(r, v, [](CdrReader& r, std::string& s) {
    s = r.read_string();
    return true;
  });
}

}  // namespace rcl

#endif  // RCLLITE__MSG_TRAITS_HPP_
